/* iframe support — used when a page is shown inside another site (Weebly).
 *
 *  • Tells the parent page how tall we are, so the iframe grows to fit and
 *    there is never a double scrollbar.
 *  • Receives the visible part of the iframe from the parent, so dialogs and
 *    the mobile menu appear where the visitor is actually looking.
 *  • Asks the parent to scroll for in-page links (#anchors).
 *
 * The matching parent-side snippet is generated by tools/build.mjs into every
 * /weebly-export/ file. Messages are namespaced "dhscs:" and carry only sizes. */
import CONFIG from '../../config.js';
import { IS_EXPORT } from './site.js';

let framed = false;
try {
  framed = window.self !== window.top;
} catch {
  framed = true; // Cross-origin parent: definitely framed.
}

export const IS_EMBEDDED = IS_EXPORT || framed;

function post(message) {
  try {
    window.parent.postMessage({ ...message, frame: window.name || '' }, '*');
  } catch {
    /* parent went away */
  }
}

/** Scroll the visitor to a y-offset inside this page (works when framed). */
export function scrollToY(top, smooth = true) {
  if (IS_EMBEDDED) post({ type: 'dhscs:scrollTo', top, smooth });
  else window.scrollTo({ top, behavior: smooth ? 'smooth' : 'auto' });
}

export function initEmbed() {
  if (!IS_EMBEDDED) return;
  const root = document.documentElement;
  root.classList.add('is-embedded');
  if (CONFIG.EMBED_SHOW_HEADER_FOOTER === false) root.classList.add('no-chrome');

  // 1. Report our height whenever it changes.
  let last = 0;
  const report = () => {
    const h = Math.ceil(document.body.getBoundingClientRect().height);
    if (Math.abs(h - last) > 1) {
      last = h;
      post({ type: 'dhscs:height', height: h });
    }
  };
  new ResizeObserver(report).observe(document.body);
  window.addEventListener('load', report);
  report();
  post({ type: 'dhscs:ready' });

  // 2. Track which slice of us is visible in the parent window.
  window.addEventListener('message', (e) => {
    const d = e.data;
    if (!d || d.type !== 'dhscs:viewport') return;
    root.style.setProperty('--vp-top', `${Math.max(0, Number(d.top) || 0)}px`);
    root.style.setProperty('--vp-height', `${Math.max(200, Number(d.height) || 0)}px`);
  });

  // 3. In-page anchor links scroll the parent instead of the (unscrollable) iframe.
  document.addEventListener('click', (e) => {
    const a = e.target.closest('a[href^="#"]');
    if (!a || a.getAttribute('href').length < 2) return;
    const target = document.getElementById(decodeURIComponent(a.getAttribute('href').slice(1)));
    if (!target) return;
    e.preventDefault();
    scrollToY(target.getBoundingClientRect().top + window.scrollY - 16);
    target.setAttribute('tabindex', target.getAttribute('tabindex') ?? '-1');
    target.focus({ preventScroll: true });
  });
}
