#!/usr/bin/env node
/* Saves a copy of the MSA master calendar to data/msa-events.json.
 *
 *   npm run msa
 *
 * The Calendar page asks Google for MSA events live, but some browsers hide or
 * rewrite the page address Google uses to check the API key, and then Google
 * refuses. In that case the site falls back to this saved copy.
 * .github/workflows/msa-calendar.yml runs this automatically every 6 hours. */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CONFIG = (await import(pathToFileURL(join(ROOT, 'config.js')).href)).default;
const CAL = CONFIG.CALENDAR;
const FILE = join(ROOT, 'data/msa-events.json');

if (!CAL.MSA_CALENDAR_ID || !CAL.CALENDAR_API_KEY) {
  console.log('No MSA calendar configured; nothing to do.');
  process.exit(0);
}

const items = [];
let pageToken = '';
do {
  const params = new URLSearchParams({
    key: process.env.CALENDAR_API_KEY || CAL.CALENDAR_API_KEY,
    singleEvents: 'true',
    orderBy: 'startTime',
    timeMin: new Date(`${CAL.RANGE.start}T00:00:00Z`).toISOString(),
    timeMax: new Date(Date.parse(`${CAL.RANGE.end}T00:00:00Z`) + 2 * 864e5).toISOString(),
    maxResults: '250',
  });
  if (pageToken) params.set('pageToken', pageToken);
  const url = `https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(CAL.MSA_CALENDAR_ID)}/events?${params}`;
  // The key is restricted to the website, so identify as the website.
  const res = await fetch(url, { headers: { referer: `${new URL(CONFIG.SITE_URL).origin}/` } });
  const json = await res.json();
  if (!res.ok) {
    console.error(`Google Calendar error ${res.status}: ${json?.error?.message || 'unknown'}`);
    process.exit(1);
  }
  for (const e of json.items || []) {
    if (e.status === 'cancelled') continue;
    items.push({ id: e.id, summary: e.summary || '', description: e.description || '', location: e.location || '', start: e.start, end: e.end });
  }
  pageToken = json.nextPageToken;
} while (pageToken);

// Only rewrite the file when the events changed (avoids empty commits).
const previous = await readFile(FILE, 'utf8').then(JSON.parse, () => ({}));
if (JSON.stringify(previous.items) === JSON.stringify(items)) {
  console.log(`MSA calendar unchanged (${items.length} events).`);
} else {
  const out = { _README: 'Generated by tools/fetch-msa.mjs (npm run msa). Do not edit by hand.', fetchedAt: new Date().toISOString(), items };
  await writeFile(FILE, `${JSON.stringify(out, null, 2)}\n`);
  console.log(`Saved ${items.length} MSA events to data/msa-events.json.`);
}
